@startuml diagramaEJ1

class Matriz {
    -int filas
    -int columnas
    -int **A
    +Matriz(int nfilas, int ncolumnas)
    +void crear()
    +void llenar()
    +void mostrar()
    +void liberar()
}

@enduml
