@startuml Ejercicio3
class Coordenada{
    -int x
    -int y
    -int z
    -int tiempo
    -bool estado_luz
    +Coordenada(int x, int y, int z, tiempo,estado_luz)
}

class Dron{
    -Coordenada *coordenadas
    +void agregar_coordenada(Coordenada c)
}
@enduml